### ISSUE TITLE
gmres solver support

### ISSUE THREAD

**Issue by Monday-Leo** [haasad/PyPardiso#65]
Hi! Currently, does PyPardiso support the gmres algorithm for solving linear equations? Generally, gmres runs much faster than LU's direct solution. At present, I am facing difficulties in solving a system of linear equations with a dimension of 1000000, while also having very high requirements for speed. I am looking forward to PyPardiso supporting the gmres algorithm.

**Comment by ma-sadeghi** [comment]
You might consider using scipy's implementation or cupy's (for GPU support).

**Comment by haasad** [comment]
Hi @Monday-Leo 

the purpose of PyPardiso is simply to use the Pardiso solver from python. There are no plans to include any other solvers. There are many other packages that provide access to various solvers and I encourage you to do some research what best fits your needs.
