### ISSUE TITLE
Error on Windows 

### ISSUE THREAD

**Issue by fbordeu** [haasad/PyPardiso#66]
Hi

I have an installation of python + mkl + pypardiso using conda-forge and I cant make pardiso to work on the example. 
This is a log to reproduce the problem. 

Any ideas???
Thanks  

C:\Users\XXXXXXX>mamba create -n PT python=3.9 mkl numpy scipy pypardiso

Looking for: ['python=3.9', 'mkl', 'numpy', 'scipy', 'pypardiso']

conda-forge/noarch                                  85.0MB @   5.9MB/s 14.5s
conda-forge/win-64                                 153.4MB @   5.0MB/s 30.9s
Transaction

  Prefix: C:\Users\XXXXXXX\AppData\Local\miniforge3\envs\PT

  Updating specs:

   - python=3.9
   - mkl
   - numpy
   - scipy
   - pypardiso

  Package                 Version  Build                  Channel           Size
----------------------------------------------------------------------------------
  Install:
----------------------------------------------------------------------------------

  + python_abi                3.9  4_cp39                 conda-forge     Cached
  + ucrt             10.0.22621.0  h57928b3_0             conda-forge     Cached
  + ca-certificates      2024.2.2  h56e8100_0             conda-forge     Cached
  + intel-openmp         2024.0.0  h57928b3_49841         conda-forge     Cached
  + vc14_runtime      14.38.33130  h82b7239_18            conda-forge     Cached
  + vs2015_runtime    14.38.33130  hcb4865c_18            conda-forge     Cached
  + vc                       14.3  hcf57466_18            conda-forge     Cached
  + libiconv                 1.17  hcfcfb64_2             conda-forge     Cached
  + pthreads-win32          2.9.1  hfa6e2cd_3             conda-forge     Cached
  + tk                     8.6.13  h5226925_1             conda-forge     Cached
  + openssl                 3.2.1  hcfcfb64_0             conda-forge     Cached
  + libsqlite              3.45.1  hcfcfb64_0             conda-forge     Cached
  + libzlib                1.2.13  hcfcfb64_5             conda-forge     Cached
  + libffi                  3.4.2  h8ffe710_5             conda-forge     Cached
  + bzip2                   1.0.8  hcfcfb64_5             conda-forge     Cached
  + xz                      5.2.6  h8d14728_0             conda-forge     Cached
  + libxml2                2.12.5  hc3477c8_0             conda-forge     Cached
  + libhwloc                2.9.3  default_haede6df_1009  conda-forge     Cached
  + tbb                 2021.11.0  h91493d7_1             conda-forge     Cached
  + mkl                  2024.0.0  h66d3029_49658         conda-forge     Cached
  + tzdata                  2024a  h0c530f3_0             conda-forge     Cached
  + llvm-meta               5.0.0  0                      conda-forge     Cached
  + python                 3.9.18  h4de0772_1_cpython     conda-forge     Cached
  + openmp                  5.0.0  vc14_1                 conda-forge     Cached
  + libflang                5.0.0  h6538335_20180525      conda-forge     Cached
  + libopenblas            0.3.26  pthreads_hc140b1d_0    conda-forge     Cached
  + libblas                 3.9.0  21_win64_openblas      conda-forge     Cached
  + libcblas                3.9.0  21_win64_openblas      conda-forge     Cached
  + liblapack               3.9.0  21_win64_openblas      conda-forge     Cached
  + numpy                  1.26.4  py39hddb5d58_0         conda-forge     Cached
  + scipy                  1.12.0  py39hddb5d58_2         conda-forge     Cached
  + pypardiso               0.4.3  pyhd8ed1ab_0           conda-forge     Cached

  Summary:

  Install: 32 packages

  Total download: 0 B

----------------------------------------------------------------------------------

Confirm changes: [Y/n] Y
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate PT

To deactivate an active environment, use

     $ mamba deactivate

C:\Users\XXXXXXX>mamba activate PT

C:\Users\XXXXXXX>python
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:29:04) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypardiso
>>> import numpy as np
>>> import scipy.sparse as sp
>>> A = sp.rand(10, 10, density=0.5, format='csr')
>>> A
<10x10 sparse matrix of type '<class 'numpy.float64'>'
        with 50 stored elements in Compressed Sparse Row format>
>>> b = np.random.rand(10)
>>> x = pypardiso.spsolve(A, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXXXXX\AppData\Local\miniforge3\envs\PT\lib\site-packages\pypardiso\scipy_aliases.py", line 46, in spsolve
    solver.factorize(A)
  File "C:\Users\XXXXXXX\AppData\Local\miniforge3\envs\PT\lib\site-packages\pypardiso\pardiso_wrapper.py", line 164, in factorize
    self._call_pardiso(A, b)
  File "C:\Users\XXXXXXX\AppData\Local\miniforge3\envs\PT\lib\site-packages\pypardiso\pardiso_wrapper.py", line 277, in _call_pardiso
    self._mkl_pardiso(self.pt.ctypes.data_as(ctypes.POINTER(self._pt_type[0])),  # pt
OSError: [WinError -1066598273] Windows Error 0xc06d007f
>>>

**Comment by ghsilva** [comment]
Long story short, I believe using MKL version 2023.2.0 or older should solve this problem while we are working in a patch release for the intel-openmp 2024.0.*

**Comment by fbordeu** [comment]
Thanks for the hint,  

I'm going to try lowering the version of intel-openmp. So this problem also exists on others OS(Linux)?

Thanks for the help

**Comment by ghsilva** [comment]
Note that MKL 2024.* requires Intel-openmp 2024.* so you will need to lower the MKL version as well.
The issue happens only on Windows.

**Comment by fbordeu** [comment]
Exactly, mamba did the correct job of  keeping my env functional by lowering ihe intel-openmp and the mkl. 

Thanks,

**Comment by haasad** [comment]
I have now also released pypardiso v0.4.4 on conda-forge, which pins MKL to `<2024`, see https://github.com/conda-forge/pypardiso-feedstock/pull/9
