### ISSUE TITLE
Allow scipy.sparse.sparray inputs

### ISSUE THREAD

**Issue by loganbvh** [haasad/PyPardiso#68]
Hi, I've opened a PR (https://github.com/haasad/PyPardiso/pull/67) that will allow inputs to PyPardiso to be of type scipy.sparse.spmatrix or scipy.sparse.sparray. scipy.sparse.sparray is recommended by scipy for new projects (see note [here](https://docs.scipy.org/doc/scipy/reference/sparse.html)).

**Comment by loganbvh** [comment]
Thanks!

**Comment by haasad** [comment]
Thank you a lot @loganbvh for the PR, I'll make a new release shortly
