### ISSUE TITLE
The Pardiso solver failed with error code -3. See Pardiso documentation for details.

### ISSUE THREAD

**Issue by XuGuang178** [haasad/PyPardiso#70]
The Pardiso solver failed with error code -3. See Pardiso documentation for details.

**Comment by haasad** [comment]
Can you give me some more info? What's your environment and operating system? The output of `pip list` or `conda list` would be helpful.

**Comment by haasad** [comment]
I'm closing this issue due to lack of information. Feel free to reopen if you have more info
